name: ci_mac

env:
  CMAKE_GENERATOR: Ninja
  CMAKE_BUILD_TYPE: Release

on:
  push:
    paths:
      - "**.txt"
      - "**.cmake"
      - ".github/workflows/ci_mac.yml"

jobs:

  macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2

    - run: brew install lapack boost ninja

    - run: ctest -S setup.cmake -VV
      env:
        FC: gfortran-11
        CC: gcc-11
        CXX: g++-11
